version: '2'

services:
  consul:
    build:
      context: .
      dockerfile: Dockerfile-consul
    container_name: consul
    hostname: consul
    command: agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data
    ports:
      - 8500:8500
    volumes:
      - consul_data:/consul/data

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
    - 1883:1883
    - 5672:5672
    - 15672:15672

volumes:
  consul_data:
  postgres_data:
  rabbitmq_data:
