version: '2'

services:
  consul:
    build:
      context: .
      dockerfile: Dockerfile-consul
    container_name: consul
    hostname: consul
    command: agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data
    volumes:
      - consul_data:/consul/data
    environment:
      VIRTUAL_HOST: consul.docker
      VIRTUAL_PORT: 8500

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    ports:
    - '1883:1883'
    - '5672:5672'
    environment:
      VIRTUAL_HOST: rabbitmq.docker
      VIRTUAL_PORT: 15672

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'

  dnsmasq:
    image: andyshinn/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - '53:53/udp'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

networks:
  default:
    external:
      name: dev

volumes:
  consul_data:
  postgres_data:
  rabbitmq_data:
